apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-crud-app
  template:
    metadata:
      labels:
        app: my-crud-app
    spec:
      containers:
      - name: my-crud-app
        image: my-crud-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "sa-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY     